# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('power', models.CharField(max_length=20, verbose_name='权限')),
            ],
            options={
                'db_table': 'cabinet',
            },
        ),
    ]
