# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0003_remove_conferenceinfo_conference_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
