# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceinfo',
            name='conference_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
