# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_conferenceinfo_conference_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceinfo',
            name='conference_time',
        ),
    ]
