# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conf_name', models.CharField(default='', max_length=255)),
                ('Crawl_url', models.CharField(default='', max_length=255)),
                ('Conf_ID', models.IntegerField()),
                ('Key_word', models.CharField(default='', max_length=30)),
                ('Conf_sponsors', models.CharField(default='', max_length=255)),
                ('Web_site', models.CharField(default='', max_length=255)),
                ('Begin_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Location', models.CharField(default='', max_length=255)),
                ('Contact', models.CharField(default='', max_length=255)),
                ('Intro', models.TextField()),
                ('Attendance', models.IntegerField()),
                ('Important_dates', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'ConferenceInfo',
            },
        ),
    ]
