# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceinfo',
            name='Detail_paper',
            field=models.CharField(default='', max_length=255),
        ),
    ]
