# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_conferenceinfo_detail_paper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceinfo',
            old_name='Key_word',
            new_name='Abbreviation',
        ),
        migrations.RenameField(
            model_name='conferenceinfo',
            old_name='Intro',
            new_name='Introduction',
        ),
    ]
